apiVersion: v1
kind: Service
metadata:
  name: myAutomatedDeployment
  namespace: namespace-workflow-1715937813952
spec:
  type: LoadBalancer
  selector:
    app: myAutomatedDeployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000